

services:
  postgres:
    container_name: postgres-sql-sgca
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: gestion_cabinet_avocat
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-sgca
    image: maildev/maildev
    ports:
      - 1080:1080 // to display the web app
      - 1025:1025 // we need to use it here in our app
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local



