spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  mvc:
    static-path-pattern: /static/**
springdoc:
  default-produces-media-type: application/json
server:
  servlet:
    context-path: /api/v1/