spring:
  main:
    allow-bean-definition-overriding: true

  jackson:
    deserialization:
      fail-on-unknown-properties: false
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  mvc:
    static-path-pattern: /static/**
springdoc:
  default-produces-media-type: application/json
server:
  servlet:
    context-path: /api/v1/
